site_name: CodigoDelSur Knowledge Base
repo_url: https://github.com/codigodelsur/knowledge-base
pages:
    - Home: index.md
    - Technologies: technologies.md
    - Git: git.md
    - Scrum: scrum.md
    - New at CodigoDelSur?: new_at_cds.md

theme: cerulean